version: '2'
services:

  api-gateway:
    build: ./account-gateway/src/main/docker/
    image: api-gateway
    container_name: api-gateway
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    extra_hosts:
      - ${APP_SERVER_NAME}:${DOCKER_HOST_IP}
    environment:
      - APP_SERVER_NAME=${APP_SERVER_NAME}
      - APP_SERVER_PORT=${APP_SERVER_PORT}

  account-api:
    build: ./account-api/src/main/docker/
    image: account-api
    container_name: account-api
    ports:
      - 8080:8080
    extra_hosts:
      - ${APP_SERVER_NAME}:${DOCKER_HOST_IP}
    environment:
      - APP_SERVER_NAME=${APP_SERVER_NAME}
      - DOCKER_HOST_IP=${DOCKER_HOST_IP}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  account-web:
    image: danjellz/http-server
    container_name: account-web
    ports:
      - 8081:8080
    volumes:
      - ./account-web:/public
    extra_hosts:
      - ${APP_SERVER_NAME}:${DOCKER_HOST_IP}
